openapi: 3.0.3
servers:
  - url: https://{environment}-euromillions-api.herokuapp.com'
    variables:
      environment:
        default: prod
        enum:
          - prod
          - staging
info:
  description: >-
    This is an public API for euromillions draws results and statistics. An REST API built to be fast, flexible and simple.
  version: 2.4.2
  title: Euromillions API
  contact:
    name: WeNeedThePoh
    url: 'https://github.com/WeNeedThePoh/euromillions-api'
paths:
  /draws:
    get:
      parameters:
      - in: query
        name: year
        required: false
        schema:
            type: integer
            minimum: 2004
      - in: query
        name: dates
        required: false
        schema:
            type: string
        examples:
          startDate:
            summary: Filter draws with a start date
            value: '2021-01-01'
          betweenDates:
            summary: Filter draws with a start date and a end date
            value: '2021-01-01,2021-02-01'
          endDate:
            summary: Filter draws with a end date
            value: ',2021-02-01'
      summary: Fetch all draws results
      tags:
        - draws
      responses:
        '200':
          description: List of all draws results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Draws'
              examples:
                draws:
                  $ref: '#/components/examples/Draws'
  /draws/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 52021
    get:
      summary: Fetch a specific draw result.
      tags:
        - draws
      responses:
        '200':
          description: Contest draw data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Draw'
              examples:
                draw:
                  $ref: '#/components/examples/Draw'

components:
  schemas:
    Draw:
      type: object
      properties:
        id:
          type: integer
        draw_id:
          type: integer
        numbers:
          type: array
        stars:
          type: array
        date:
          type: string
        prize:
          type: integer
        has_winner:
          type: boolean
    Draws:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          draw_id:
            type: integer
          numbers:
            type: array
          stars:
            type: array
          date:
            type: string
          prize:
            type: integer
          has_winner:
            type: boolean
  examples:
    Draw:
      value:
        {
          "id": 12,
          "draw_id": 262021,
          "numbers": [1, 5, 24, 50, 42],
          "stars": [2, 6],
          "date": "2021-02-04",
          "prize": 120000000,
          "has_winner": false
        }

    Draws:
      value:
        [
            {
                "id": 1,
                "draw_id": 262021,
                "numbers": [1, 5, 24, 50, 42],
                "stars": [2, 6],
                "date": "2021-02-04",
                "prize": 120000000,
                "has_winner": false
            },
            {
                "id": 2,
                "draw_id": 272021,
                "numbers": [7, 26, 34, 30, 46],
                "stars": [1, 10],
                "date": "2021-02-08",
                "prize": 150000000,
                "has_winner": true
            },
            {
                "id": 3,
                "draw_id": 282021,
                "numbers": [20, 25, 34, 10, 22],
                "stars": [4, 7],
                "date": "2021-02-15",
                "prize": 15000000,
                "has_winner": false
            }
        ]
