openapi: 3.1.0
servers:
  - url: 'https://euro-millions-api.herokuapp.com'
info:
  description: >-
    This is an public API for euromillions draws results and statistics. An REST API built to be fast, flexible and simple.
  version: 0.1.0
  title: Euromillions API
  contact:
    name: WeNeedThePoh
    url: 'https://github.com/WeNeedThePoh'
paths:
  /draws:
    get:
      parameters:
      - in: query
        name: year
        required: false
        schema:
            type: integer
            minimum: 2004
      - in: query
        name: dates
        required: false
        schema:
            type: string
      summary: Fetch all draws results
      tags:
        - draws
      responses:
        '200':
          description: List of all draws results
          content:
            application/json:
              schema:
                $ref: 'schemas/draw.yaml'
              example:
                $ref: 'examples/draws.json'
    post:
      summary: Fetch and add new draws results. This is a cron job.
      tags:
        - draws
      responses:
        '201':
          description: The new draws were successfully parsed and inserted.
  /draws/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 52021
    get:
      summary: Fetch a specific draw result.
      tags:
        - draws
      responses:
        '200':
          description: Contest draw data.
          content:
            application/json:
              schema:
                $ref: 'schemas/draw.yaml'
              example:
                $ref: 'examples/draw.json'