---
name: Crontab

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  add-draws:
    name: Add new draws
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    # - name: Run add_draws script in Prod
    #   run: flyctl ssh console -a prod-euromillions-api -C "sh app/scripts/cronjobs/add_draws.sh"
    #   env:
    #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Run add_draws script in Staging
      run: flyctl ssh console -a staging-euromillions-api -C "sh app/scripts/cronjobs/add_draws.sh"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
