name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_TOKEN }}
          oas-file-path: './docs/api.yaml'
          api-version: 'v2.3'
