name: Open API docs
on:
  release:
    types: [published]
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_TOKEN }}
          oas-file-path: './docs/api.yaml'
