name: Release
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  terraform:
    name: Execute Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: configs/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.0

      - name: Terraform Init
        run: terraform init -backend-config="conn_str=postgres://${{ secrets.TF_STATE_DB_USERNAME }}:${{ secrets.TF_STATE_DB_PASSWORD }}@${{ secrets.TF_STATE_DB_HOST }}:${{ secrets.TF_STATE_DB_PORT }}/${{ secrets.TF_STATE_DB_NAME }}?sslmode=disable"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_WORKSPACE: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy api
        run: |
          flyctl deploy --now -a prod-euromillions-api \
            -i ${{ env.REGISTRY }}/weneedthepoh/euromillions-api:${{ github.sha }} \
            -e EUROMILLIONS_MIN_YEAR=2004 \
            -e EUROMILLIONS_WEB_BASE_URL=https://www.euro-millions.com \
            -e FLASK_APP=euromillions_api \
            -e FLASK_ENV=development \
            -e DB_NAME=${{ secrets.PROD_DB_NAME }} \
            -e DB_SCHEMA=${{ secrets.PROD_DB_SCHEMA }} \
            -e DB_USER=${{ secrets.PROD_DB_USER }} \
            -e DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.PROD_DB_HOST }} \
            -e DB_PORT=${{ secrets.PROD_DB_PORT }}
